esphome:
  name: test-all

external_components:
  - source:
      type: local
      path: ../components

esp32:
  board: esp32dev
  framework:
    type: arduino

remote_transmitter:
  id: ir_led
  pin: 4
  carrier_duty_percent: 50%

climate:
  - platform: electra
    id: my_electra
    name: 'Electra'

  - platform: fujitsu
    id: my_fujitsu
    model: ARREB1E
    name: 'Fujitsu'

  - platform: panasonic
    id: my_panasonic
    model: DKE
    name: 'Panasonic'

  - platform: sharp
    id: my_sharp
    model: A705
    name: 'Sharp'

  - platform: mitsubishi
    id: my_mitsubishi_ac
    model: MITSUBISHI_AC
    name: 'Mitsubishi AC'

  - platform: mitsubishi
    id: my_mitsubishi_136
    model: MITSUBISHI136
    name: 'Mitsubishi 136'

  - platform: mitsubishi
    id: my_mitsubishi_112
    model: MITSUBISHI112
    name: 'Mitsubishi 112'

button:
  - platform: template
    name: 'Step vertical'
    on_press:
      then:
        - lambda: |-
            id(my_fujitsu).step_vertical();
