esphome:
  name: ac-panasonic

external_components:
  - source:
      type: local
      path: ../components

esp32:
  board: esp32dev
  framework:
    type: arduino

remote_transmitter:
  id: ir_led
  pin: 4
  carrier_duty_percent: 50%

climate:
  - platform: panasonic
    id: my_climate
    model: DKE
    name: 'AC'
