name: ESPHome Build Validation

on:
  push:
    branches:
      - '*'
    paths-ignore:
      - 'README.md'
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.13'
          cache: 'pip'

      - name: Install ESPHome
        run: |
          pip install -r requirements.txt

      - name: Cache PlatformIO
        uses: actions/cache@v5
        with:
          path: ~/.platformio
          key: ${{ runner.os }}-platformio-${{ hashFiles('configurations/*.yaml', 'requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-platformio-

      - name: Run ESPHome Validate
        run: |
          for config in ./configurations/*.yaml; do
            echo "--- Processing $config ---"
            esphome config "$config"
          done

      - name: Run ESPHome Compile
        run: |
          for config in ./configurations/*.yaml; do
            echo "--- Processing $config ---"
            esphome compile "$config"
          done

  contrib-readme:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write

    if: github.repository == 'mistic100/ESPHome-IRremoteESP8266' && github.event_name == 'push' && github.ref_name == 'main'

    steps:
        - name: Update contributors
          uses: akhilmhdh/contributors-readme-action@v2.3.11
          env:
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
